#!/usr/bin/env bash
# Sync the central lessons library into THIS repo's .claude/review/LESSONS.md.
# Includes the agnostic lessons plus only the languages this repo actually uses.
# Run from inside a repo:  sync-lessons.sh
# Requires: git; reads ~/.claude/lessons produced by mine-all-repos.sh
set -euo pipefail

LESSONS_DIR="${LESSONS_DIR:-$HOME/.claude/lessons}"
ROOT="$(git rev-parse --show-toplevel)"
OUT="$ROOT/.claude/review/LESSONS.md"
mkdir -p "$ROOT/.claude/review"

[ -d "$LESSONS_DIR" ] || { echo "No lessons library at $LESSONS_DIR. Run mine-all-repos.sh first."; exit 1; }

# Detect languages present in the repo's tracked files (top extensions).
detect_langs() {
  git ls-files \
  | sed -n 's/.*\.\([A-Za-z0-9]*\)$/\1/p' \
  | while read -r ext; do
      case "$ext" in
        py) echo python ;; go) echo go ;;
        ts|tsx) echo typescript ;; js|jsx|mjs) echo javascript ;;
        rb) echo ruby ;; rs) echo rust ;; java) echo java ;;
        kt) echo kotlin ;; c|h) echo c ;; cpp|cc|hpp) echo cpp ;;
        cs) echo csharp ;; php) echo php ;; swift) echo swift ;;
        scala) echo scala ;; sh|bash) echo shell ;;
      esac
    done | sort | uniq -c | sort -rn | awk '$1 >= 3 {print $2}'
  # threshold: at least 3 files of a language before we pull its lessons
}

LANGS="$(detect_langs)"
echo "Languages detected in $(basename "$ROOT"): ${LANGS:-none}"

{
  echo "<!-- Generated by sync-lessons.sh from $LESSONS_DIR — do not edit by hand. -->"
  echo
  [ -f "$LESSONS_DIR/AGNOSTIC.md" ] && cat "$LESSONS_DIR/AGNOSTIC.md" && echo
  for lang in $LANGS; do
    if [ -f "$LESSONS_DIR/$lang.md" ]; then
      cat "$LESSONS_DIR/$lang.md"; echo
    fi
  done
} > "$OUT"

echo "Wrote $OUT"
echo "(the pre-push reviewer already loads LESSONS.md automatically)"
